sudo: required
services:
  - docker

before_install:
  - docker build -t DeemiTx/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev ./client

  script:
    - docker run -e CI=true DeemiTx/react-test npm test

after_success:
  - docker build -t DeemiTx/multi-client ./client
  - docker build -t DeemiTx/multi-nginx ./nginx
  - docker build -t DeemiTx/multi-server ./server
  - docker build -t DeemiTx/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push DeemiTx/multi-client
  - docker push DeemiTx/multi-nginx
  - docker push DeemiTx/multi-server
  - docker push DeemiTx/multi-worker
